# install tidyverse
install.packages("tidyverse")
library(tidyverse)
# install remotes
install.packages("remotes")
# install data
remotes::install_github("allisonhorst/palmerpenguins")
library(palmerpenguins)
penguins
# check data import
library(palmerpenguins)
penguins
# double check data import
glimpse(penguins)

ggplot(data = penguins, 
aes(x = bill_length_mm, y = bill_depth_mm)) +
geom_point(aes(color = species, shape = species),
size = 3, alpha = 0.8) + 
#theme_minimal() +
scale_color_manual(values = c("darkorange", "purple", "cyan4")) +
labs(title = "Bill size, Palmer Station LTER",
subtitle = "Bill length and bill depth for Adelie, Chinstrap, and Gentoo Penguins",
x = "Bill length (mm)",
y = "Bill depth (mm) ",
color = "Penguin species",
shape = "Penguin species") +
theme_minimal()

#Variable Class
class(penguins$sex)
class(penguins$body_mass_g)
class(penguins$species)
class(penguins$island)
class(penguins$bill_length_mm)
class(penguins$bill_depth_mm)
class(penguins$flipper_length_mm)
#Variable Levels
levels(penguins$sex)
levels(penguins$body_mass_g)
levels(penguins$species)
levels(penguins$island)
levels(penguins$bill_length_mm)
levels(penguins$bill_depth_mm)
levels(penguins$flipper_length_mm)

# Bar graph counts > colorblind palettes
penguins %>%
  count(species) %>%
  ggplot() + geom_col(aes(x = species, y = n, fill = species)) + geom_label(aes(x = species, y = n, label = n))+scale_fill_manual(values = c("coral2","darkseagreen3","darkslategray3")) + theme_minimal() + labs(title = 'Species Population')


summary(penguins$species)
summary(penguins$island)
summary(penguins$sex)
summary(penguins)

mod_adelie <- lm(penguins$body_mass_g[penguins$species == "Adelie"] ~ penguins$flipper_length_mm[penguins$species == "Adelie"])
summary(mod_adelie)
mod_adelie$coef
plot(penguins$flipper_length_mm[penguins$species == "Adelie"],penguins$body_mass_g[penguins$species == "Adelie"],main = "Scatterplot")
abline(mod_adelie)

mod_chinstrap <- lm(penguins$body_mass_g[penguins$species == "Chinstrap"] ~ penguins$flipper_length_mm[penguins$species == "Chinstrap"])
summary(mod_chinstrap)
mod_chinstrap$coef
plot(penguins$flipper_length_mm[penguins$species == "Chinstrap"],penguins$body_mass_g[penguins$species == "Chinstrap"],main = "Scatterplot")
abline(mod_chinstrap)

mod_gentoo <- lm(penguins$body_mass_g[penguins$species == "Gentoo"] ~ penguins$flipper_length_mm[penguins$species == "Gentoo"])
summary(mod_gentoo)
mod_gentoo$coef
plot(penguins$flipper_length_mm[penguins$species == "Gentoo"],penguins$body_mass_g[penguins$species == "Gentoo"],main = "Scatterplot")
abline(mod_gentoo)

penguins %>%
  count(species[sex]) %>%
  ggplot() + geom_bar(penguins, mapping = aes(x = species, fill = sex),position="stack")



